// Generated by view binder compiler. Do not edit!
package app.altamira.com.minitwitter.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.Spinner;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import app.altamira.com.minitwitter.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityEscanerBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonEscanear;

  @NonNull
  public final EditText editTextDescripcion;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final Spinner spInventarios;

  @NonNull
  public final TextView textViewNombreCompleto;

  private ActivityEscanerBinding(@NonNull ConstraintLayout rootView, @NonNull Button buttonEscanear,
      @NonNull EditText editTextDescripcion, @NonNull ImageView imageView2,
      @NonNull Spinner spInventarios, @NonNull TextView textViewNombreCompleto) {
    this.rootView = rootView;
    this.buttonEscanear = buttonEscanear;
    this.editTextDescripcion = editTextDescripcion;
    this.imageView2 = imageView2;
    this.spInventarios = spInventarios;
    this.textViewNombreCompleto = textViewNombreCompleto;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityEscanerBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityEscanerBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_escaner, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityEscanerBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonEscanear;
      Button buttonEscanear = ViewBindings.findChildViewById(rootView, id);
      if (buttonEscanear == null) {
        break missingId;
      }

      id = R.id.editTextDescripcion;
      EditText editTextDescripcion = ViewBindings.findChildViewById(rootView, id);
      if (editTextDescripcion == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.spInventarios;
      Spinner spInventarios = ViewBindings.findChildViewById(rootView, id);
      if (spInventarios == null) {
        break missingId;
      }

      id = R.id.textViewNombreCompleto;
      TextView textViewNombreCompleto = ViewBindings.findChildViewById(rootView, id);
      if (textViewNombreCompleto == null) {
        break missingId;
      }

      return new ActivityEscanerBinding((ConstraintLayout) rootView, buttonEscanear,
          editTextDescripcion, imageView2, spInventarios, textViewNombreCompleto);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
