// Generated by view binder compiler. Do not edit!
package app.altamira.com.minitwitter.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import app.altamira.com.minitwitter.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySignUpBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonRegistro;

  @NonNull
  public final EditText editTextApellido;

  @NonNull
  public final EditText editTextEmail;

  @NonNull
  public final EditText editTextNombre;

  @NonNull
  public final EditText editTextPassword;

  @NonNull
  public final EditText editTextUsuario;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final TextView textViewLogin;

  private ActivitySignUpBinding(@NonNull ConstraintLayout rootView, @NonNull Button buttonRegistro,
      @NonNull EditText editTextApellido, @NonNull EditText editTextEmail,
      @NonNull EditText editTextNombre, @NonNull EditText editTextPassword,
      @NonNull EditText editTextUsuario, @NonNull ImageView imageView,
      @NonNull TextView textViewLogin) {
    this.rootView = rootView;
    this.buttonRegistro = buttonRegistro;
    this.editTextApellido = editTextApellido;
    this.editTextEmail = editTextEmail;
    this.editTextNombre = editTextNombre;
    this.editTextPassword = editTextPassword;
    this.editTextUsuario = editTextUsuario;
    this.imageView = imageView;
    this.textViewLogin = textViewLogin;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySignUpBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySignUpBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_sign_up, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySignUpBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonRegistro;
      Button buttonRegistro = ViewBindings.findChildViewById(rootView, id);
      if (buttonRegistro == null) {
        break missingId;
      }

      id = R.id.editTextApellido;
      EditText editTextApellido = ViewBindings.findChildViewById(rootView, id);
      if (editTextApellido == null) {
        break missingId;
      }

      id = R.id.editTextEmail;
      EditText editTextEmail = ViewBindings.findChildViewById(rootView, id);
      if (editTextEmail == null) {
        break missingId;
      }

      id = R.id.editTextNombre;
      EditText editTextNombre = ViewBindings.findChildViewById(rootView, id);
      if (editTextNombre == null) {
        break missingId;
      }

      id = R.id.editTextPassword;
      EditText editTextPassword = ViewBindings.findChildViewById(rootView, id);
      if (editTextPassword == null) {
        break missingId;
      }

      id = R.id.editTextUsuario;
      EditText editTextUsuario = ViewBindings.findChildViewById(rootView, id);
      if (editTextUsuario == null) {
        break missingId;
      }

      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.textViewLogin;
      TextView textViewLogin = ViewBindings.findChildViewById(rootView, id);
      if (textViewLogin == null) {
        break missingId;
      }

      return new ActivitySignUpBinding((ConstraintLayout) rootView, buttonRegistro,
          editTextApellido, editTextEmail, editTextNombre, editTextPassword, editTextUsuario,
          imageView, textViewLogin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
